import datetime
from django.test import TestCase, Client
from django.contrib.auth.models import User, Group
from django.core.exceptions import ValidationError
from django.urls import reverse
from hms_app.models import Department, DoctorProfile, PatientProfile, Appointment, MedicalRecord

class HMSModelAndSecurityTests(TestCase):
    def setUp(self):
        self.client = Client()

        # Groups
        self.receptionist_group = Group.objects.create(name='Receptionists')
        self.doctor_group = Group.objects.create(name='Doctors')
        self.patient_group = Group.objects.create(name='Patients')

        # Department
        self.dept = Department.objects.create(name='Cardiology')

        # Users
        self.rec_user = User.objects.create_user('rec_test', 'rec@test.com', 'pass123')
        self.rec_user.groups.add(self.receptionist_group)

        self.doc_user = User.objects.create_user('doc_test', 'doc@test.com', 'pass123', first_name='John', last_name='Smith')
        self.doc_user.groups.add(self.doctor_group)
        self.doctor = DoctorProfile.objects.create(user=self.doc_user, department=self.dept, specialization='Cardiology', consultation_fee=500.00)

        self.pat_user = User.objects.create_user('pat_test', 'pat@test.com', 'pass123', first_name='Alice', last_name='Wonderland')
        self.pat_user.groups.add(self.patient_group)
        self.patient = PatientProfile.objects.create(
            user=self.pat_user,
            date_of_birth=datetime.date(1990, 1, 1),
            gender='F',
            blood_group='O+',
            emergency_contact='9999999999'
        )

    def test_patient_id_autogenerated(self):
        self.assertTrue(self.patient.patient_id.startswith('PAT-'))

    def test_double_booking_prevention(self):
        tomorrow = datetime.date.today() + datetime.timedelta(days=1)
        time_slot = datetime.time(10, 0, 0)

        # First appointment
        apt1 = Appointment.objects.create(
            patient=self.patient,
            doctor=self.doctor,
            appointment_date=tomorrow,
            time_slot=time_slot,
            status='SCHEDULED'
        )
        self.assertIsNotNone(apt1.id)

        # Attempt to create conflicting appointment with same doctor, date, and time
        apt2 = Appointment(
            patient=self.patient,
            doctor=self.doctor,
            appointment_date=tomorrow,
            time_slot=time_slot,
            status='SCHEDULED'
        )
        with self.assertRaises(ValidationError):
            apt2.clean()

    def test_medical_record_billing_auto_calculation(self):
        tomorrow = datetime.date.today() + datetime.timedelta(days=1)
        apt = Appointment.objects.create(
            patient=self.patient,
            doctor=self.doctor,
            appointment_date=tomorrow,
            time_slot=datetime.time(14, 0, 0),
            status='SCHEDULED'
        )
        rec = MedicalRecord.objects.create(
            appointment=apt,
            symptoms='Fever',
            diagnosis='Viral',
            prescription='Rest',
            consultation_fee=500.00,
            medicine_fee=150.00
        )
        self.assertEqual(rec.total_amount, 650.00)

    def test_rbac_patient_forbidden_on_receptionist_dashboard(self):
        self.client.login(username='pat_test', password='pass123')
        response = self.client.get(reverse('receptionist_dashboard'))
        self.assertEqual(response.status_code, 403)

    def test_receptionist_can_access_receptionist_dashboard(self):
        self.client.login(username='rec_test', password='pass123')
        response = self.client.get(reverse('receptionist_dashboard'))
        self.assertEqual(response.status_code, 200)
